name: Heroku Dyno Scheduler

on:
  schedule:
    - cron: '0 4 * * *' # 6:00 AM Poland time (UTC+2 in summer, UTC+1 in winter)
    - cron: '0 21 * * *' # 11:00 PM Poland time
  workflow_dispatch:

jobs:
  scale-up:
    if: github.event.schedule == '0 4 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Scale up Heroku dyno
        run: heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  scale-down:
    if: github.event.schedule == '0 21 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Scale down Heroku dyno
        run: heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
