name: Heroku Dyno Scheduler

on:
  schedule:
    - cron: '0 4 * * 1-5' # 6:00 AM local (summer)
    - cron: '0 22 * * 1-5' # 12:00 AM local (summer)
    - cron: '0 13 * * 1-5' # 3:00 PM local (summer)
    - cron: '0 19 * * 1-5' # 9:00 PM local (summer)
    - cron: '0 16 * * 6,0' # 6:00 PM local (summer)
    - cron: '0 19 * * 6,0' # 9:00 PM local (summer)
  workflow_dispatch:

jobs:
  scale:
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Scale Heroku dyno up or down
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Determine action based on schedule time
          HOUR=$(date -u +%H)
          DOW=$(date -u +%u) # 1=Mon ... 7=Sun
          ACTION="down"
          # Weekday morning start
          if [[ "$DOW" -ge 1 && "$DOW" -le 5 && "$HOUR" == "04" ]]; then ACTION="up"; fi
          # Weekday midday stop
          if [[ "$DOW" -ge 1 && "$DOW" -le 5 && "$HOUR" == "22" ]]; then ACTION="down"; fi
          # Weekday afternoon start
          if [[ "$DOW" -ge 1 && "$DOW" -le 5 && "$HOUR" == "13" ]]; then ACTION="up"; fi
          # Weekday evening stop
          if [[ "$DOW" -ge 1 && "$DOW" -le 5 && "$HOUR" == "19" ]]; then ACTION="down"; fi
          # Weekend evening start
          if ([[ "$DOW" == "6" ]] || [[ "$DOW" == "7" ]]) && [[ "$HOUR" == "16" ]]; then ACTION="up"; fi
          # Weekend evening stop
          if ([[ "$DOW" == "6" ]] || [[ "$DOW" == "7" ]]) && [[ "$HOUR" == "19" ]]; then ACTION="down"; fi
          if [[ "$ACTION" == "up" ]]; then
            heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}
          else
            heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME }}
          fi
